export const INVALID_CREDENTIALS = "INVCRED01";
export const ACCOUNT_LOCKED = "LOCKER01";
export const INVALID_SUBSCRIPTION = "UNSUBS56";
export const SERVER_PROBLEM = "SERVER_ERR_001";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const DUPLICATE_FOUND = "DUPLICATE_FOUND";
export const INVALID_DATABASE_PROCESS = "DATABASE_ROLLBACK_PROCESS";
export const FIALED_DATABASE_PROCESS = "FAILED_DATABASE_PROCESS";
export const INVALID_IDENTITY = "INVALID_IDENTITY";
export const MIDTRANS_ERROR = "PAYMENTSHIP_FAILED";
export const NULL_DATA = "NULL_DATA";
export const INVALID_PARAMS = "INVALID_PARAMS_FORMAT";

